name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast:
    name: Run SAST with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'  # ปรับเป็นภาษาของโปรเจกต์ เช่น python, java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  sca:
    name: Run SCA with Snyk
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Run Snyk test
        uses: snyk/actions@v2
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
